version: '3.8'

services:
  listener:
    build:
      context: .
    ports:
      - "8002:8000"
    environment:
      - PYTHON_ENVIRONMENT=../app
      - GEMINI_API_KEY=AIzaSyClHzrHzfj9CVJ70N0Lj_FnG1bglaKCNJA
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./database:/app/database
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_URL=postgresql://postgres:password@postgres:5432/sla_monitor
